/**
 * @file        [Configuration]
 * @brief
 * @version     [Version number]
 * @author      [Fill implementers name]
 * @date        05th July 2021
 * @author      None
 * @date        None
 * @copyright   SEDEMAC Mechatronics Pvt Ltd
 **/
#ifndef _CONFIGURATION_H_
#define _CONFIGURATION_H_

#pragma once

#include "productSelection.h"

#define TARGET_DESKTOP  1
#define TARGET_GCU      2

// use TARGET_DESKTOP for (partial) validation on computer
// use TARGET_GCU for validation on GCU
#define RUNNING_ON                      TARGET_GCU
#define MENU_STACK_DEPTH                    4
#define STRING_PARAM_MAX_LEN               20
#define MAX_EDITABLE_ITEMS_PER_SCREEN       3
#define MAX_MENU_ITEMS                     55

//#define SUBMENUS_IN_MODULE                  6
#define SUBMENUS_IN_MODULE                  7
#define SUBMENUS_IN_INPUTS                 18
#define SUBMENUS_IN_OUTPUTS                 9
#define SUBMENUS_IN_TIMERS                  2
#define SUBMENUS_IN_GENERATOR               6
#define SUBMENUS_IN_MAINS                   5
#define SUBMENUS_IN_ENGINE                  9
#define SUBMENUS_IN_MAINTENANCE             2
#define SUBMENUS_IN_ID                      3
#define SUBMENUS_IN_MISC                    1

 /*Module*/
#define LEAFNODES_IN_GENERAL                4
#define LEAFNODES_IN_DISPLAY                2
#define LEAFNODES_IN_MODBUS_COMM            4
#define LEAFNODES_IN_BTS_CONFIG             4
#define LEAFNODES_IN_CYCLIC_CONFIG          3
#define LEAFNODES_IN_NIGHT_MODE_CONFG       3
#define LEAFNODES_IN_AUTO_MD_SWITCH         3
 /*Inputs*/
#define LEAFNODES_IN_DIG_IN_A               5
#define LEAFNODES_IN_DIG_IN_B               5
#define LEAFNODES_IN_DIG_IN_C               5
#define LEAFNODES_IN_DIG_IN_D               5
#define LEAFNODES_IN_DIG_IN_E               5
#define LEAFNODES_IN_DIG_IN_F               5
#define LEAFNODES_IN_DIG_IN_G               5
#define LEAFNODES_IN_DIG_IN_H               5
#define LEAFNODES_IN_DIG_IN_I               5
#define LEAFNODES_IN_LOP_RES_DIG_J         27
#define LEAFNODES_IN_FUEL_LVL_DIG_K        55
#define LEAFNODES_IN_ENG_TEMP_DIG_L        27
#define LEAFNODES_IN_SHEL_TEMP_DIG_M       31
#define LEAFNODES_IN_AUX_S2_RES_DIG_N      30
#define LEAFNODES_IN_AUX_S3_DIG_O          27
#define LEAFNODES_IN_AUX_S4_DIG_P          22
#define LEAFNODES_IN_DIG_IN_Q               5
#define LEAFNODES_IN_DIG_IN_R               5
 /*Outputs*/
#define LEAFNODES_IN_OUT_A                  2
#define LEAFNODES_IN_OUT_B                  2
#define LEAFNODES_IN_OUT_C                  2
#define LEAFNODES_IN_OUT_D                  2
#define LEAFNODES_IN_OUT_E                  2
#define LEAFNODES_IN_OUT_F                  2
#define LEAFNODES_IN_OUT_G                  2
#define LEAFNODES_IN_OUT_H                  2
#define LEAFNODES_IN_OUT_I                  2
 /*Timer*/
#define LEAFNODES_IN_CRANKING_TIMER         4
#define LEAFNODES_IN_GENERAL_TIMER         13
 /*Generator*/
#define LEAFNODES_IN_ALT_CONFIG             9
#define LEAFNODES_IN_VOLT_MONITOR           8
#define LEAFNODES_IN_FREQ_MONITOR           8
#define LEAFNODES_IN_CURRENT_MONITOR        6
#define LEAFNODES_IN_FAN_CURR_MONITOR       7
#define LEAFNODES_IN_LOAD_MONITOR           9
 /*Mains*/
#define LEAFNODES_IN_MAINS_CONFIG           5
#define LEAFNODES_IN_UNDER_VOLT_MON         3
#define LEAFNODES_IN_OVER_VOLT_MON          3
#define LEAFNODES_IN_UNDER_FREQ_MON         3
#define LEAFNODES_IN_OVER_FREQ_MON          3
 /*Engine*/
#define LEAFNODES_IN_CRANK_DISCONN          11
#define LEAFNODES_IN_SPEED_MONITOR          7/*8*/
#define LEAFNODES_IN_BATTERY_MONITOR        6
#define LEAFNODES_IN_CHARGE_ALT_MON         3
#define LEAFNODES_IN_PREHEAT                4
/*ECU*/
#define LEAFNODES_IN_ECU                    24
#define LEAFNODES_IN_LOP_FROM_ECU           4
#define LEAFNODES_IN_COOL_TEMP_ECU          4
#define LEAFNODES_IN_LOT_ECU                4
/*EGR Fault Monitoring Timers*/
#define LEAFNODES_IN_EGR_FAULT_MON          4
/*Maintenance*/
#define LEAFNODES_IN_MAINT_ALARM            2
#define LEAFNODES_IN_ALARM_DUE_DATE         1
 /*ID*/
#define LEAFNODES_IN_ENG_SR_NO              1
#define LEAFNODES_IN_PASSWORD_1             1
#define LEAFNODES_IN_PASSWORD_2             1
 /*Slect Profile*/
#define LEAFNODES_IN_SELECT_PROFILE         1

 typedef enum
   {
       UI_STATE_INITIALIZING,
       UI_STATE_SHOWING_MENU,
       UI_STATE_SHOWING_SCREEN_ITEM_SELECTION,
       UI_STATE_SHOWING_SCREEN_ITEM_EDIT
   } UI_STATES_t;

   enum
   {
       SID_GENERAL_PROFILE_NAME,
       SID_GENERAL_POWER_ON_MODE,
       SID_GENERAL_POWER_ON_LAMP_TEST,
       SID_GENERAL_PASSWORD_LOCK,

       SID_DISPLAY_CONTRAST,
       SID_DISPLAY_POWER_SAVE_MODE,

       SID_MODBUS_COMM_COMM_MODE,
       SID_MODBUS_COMM_MODBUS_SLAVE_ID,
       SID_MODBUS_COMM_MODBUS_BAUDRATE,
       SID_MODBUS_COMM_PARITY,

       SID_BTS_CONFIG_BATTERY_MON,
       SID_BTS_CONFIG_LOW_BATT_THRESHOLD,
       SID_BTS_CONFIG_LOW_BATT_MON_DELAY,
       SID_BTS_CONFIG_DG_RUN_DURATION,

       SID_CYCLIC_CONFIG_CYCLIC_MODE,
       SID_CYCLIC_CONFIG_DG_OFF_DURATION,
       SID_CYCLIC_CONFIG_DG_ON_DURATION,

       SID_NIGHT_MODE_CONFG_NIGHT_MODE,
       SID_NIGHT_MODE_CONFG_START_TIME,
       SID_NIGHT_MODE_CONFG_OFF_DURATION,

       SID_AUTO_MD_SWITCH_AUTO_MD_SWITCH,
       SID_AUTO_MD_SWITCH_MANUAL_MODE_TIME,
       SID_AUTO_MD_SWITCH_OUTPUT_ON_TIME,

       SID_DIG_IN_A_SOURCE,
       SID_DIG_IN_A_POLARITY,
       SID_DIG_IN_A_ACTION,
       SID_DIG_IN_A_ACTIVATION,
       SID_DIG_IN_A_ACTIVATION_DELAY,
       SID_DIG_IN_B_SOURCE,
       SID_DIG_IN_B_POLARITY,
       SID_DIG_IN_B_ACTION,
       SID_DIG_IN_B_ACTIVATION,
       SID_DIG_IN_B_ACTIVATION_DELAY,
       SID_DIG_IN_C_SOURCE,
       SID_DIG_IN_C_POLARITY,
       SID_DIG_IN_C_ACTION,
       SID_DIG_IN_C_ACTIVATION,
       SID_DIG_IN_C_ACTIVATION_DELAY,
       SID_DIG_IN_D_SOURCE,
       SID_DIG_IN_D_POLARITY,
       SID_DIG_IN_D_ACTION,
       SID_DIG_IN_D_ACTIVATION,
       SID_DIG_IN_D_ACTIVATION_DELAY,
       SID_DIG_IN_E_SOURCE,
       SID_DIG_IN_E_POLARITY,
       SID_DIG_IN_E_ACTION,
       SID_DIG_IN_E_ACTIVATION,
       SID_DIG_IN_E_ACTIVATION_DELAY,
       SID_DIG_IN_F_SOURCE,
       SID_DIG_IN_F_POLARITY,
       SID_DIG_IN_F_ACTION,
       SID_DIG_IN_F_ACTIVATION,
       SID_DIG_IN_F_ACTIVATION_DELAY,
       SID_DIG_IN_G_SOURCE,
       SID_DIG_IN_G_POLARITY,
       SID_DIG_IN_G_ACTION,
       SID_DIG_IN_G_ACTIVATION,
       SID_DIG_IN_G_ACTIVATION_DELAY,
       SID_DIG_IN_H_SOURCE,
       SID_DIG_IN_H_POLARITY,
       SID_DIG_IN_H_ACTION,
       SID_DIG_IN_H_ACTIVATION,
       SID_DIG_IN_H_ACTIVATION_DELAY,
       SID_DIG_IN_I_SOURCE,
       SID_DIG_IN_I_POLARITY,
       SID_DIG_IN_I_ACTION,
       SID_DIG_IN_I_ACTIVATION,
       SID_DIG_IN_I_ACTIVATION_DELAY,

       SID_LOP_RES_DIG_J_SENSOR_SELECTION,
       SID_LOP_RES_DIG_J_DIG_SOURCE,
       SID_LOP_RES_DIG_J_DIG_POLARITY,
       SID_LOP_RES_DIG_J_DIG_ACTION,
       SID_LOP_RES_DIG_J_DIG_ACTIVATION,
       SID_LOP_RES_DIG_J_DIG_ACTIVATION_DELAY,
       SID_LOP_RES_DIG_J_CIRCUIT_FAULT_ACTION,
       SID_LOP_RES_DIG_J_R1,
       SID_LOP_RES_DIG_J_V1,
       SID_LOP_RES_DIG_J_R2,
       SID_LOP_RES_DIG_J_V2,
       SID_LOP_RES_DIG_J_R3,
       SID_LOP_RES_DIG_J_V3,
       SID_LOP_RES_DIG_J_R4,
       SID_LOP_RES_DIG_J_V4,
       SID_LOP_RES_DIG_J_R5,
       SID_LOP_RES_DIG_J_V5,
       SID_LOP_RES_DIG_J_R6,
       SID_LOP_RES_DIG_J_V6,
       SID_LOP_RES_DIG_J_R7,
       SID_LOP_RES_DIG_J_V7,
       SID_LOP_RES_DIG_J_R8,
       SID_LOP_RES_DIG_J_V8,
       SID_LOP_RES_DIG_J_R9,
       SID_LOP_RES_DIG_J_V9,
       SID_LOP_RES_DIG_J_R10,
       SID_LOP_RES_DIG_J_V10,

       SID_FUEL_LVL_DIG_K_SENSOR_SELECTION,
       SID_FUEL_LVL_DIG_K_DIG_SOURCE,
       SID_FUEL_LVL_DIG_K_DIG_POLARITY,
       SID_FUEL_LVL_DIG_K_DIG_ACTION,
       SID_FUEL_LVL_DIG_K_DIG_ACTIVATION,
       SID_FUEL_LVL_DIG_K_DIG_ACTIVATION_DELAY,
       SID_FUEL_LVL_DIG_K_SHUTDOWN,
       SID_FUEL_LVL_DIG_K_SHUTDOWN_THRESHOLD,
       SID_FUEL_LVL_DIG_K_NOTIFICATION,
       SID_FUEL_LVL_DIG_K_NOTIFICATION_THRESHOLD,
       SID_FUEL_LVL_DIG_K_FUEL_TANK_CAPACITY,
       SID_FUEL_LVL_DIG_K_FUEL_THEFT_WARNING,
       SID_FUEL_LVL_DIG_K_FUEL_THEFT_THRESHOLD,
       SID_FUEL_LVL_DIG_K_FUEL_CONSUMPTION,
       SID_FUEL_LVL_DIG_K_FUEL_IN_PCT,
       SID_FUEL_LVL_DIG_K_R1,
       SID_FUEL_LVL_DIG_K_L1,
       SID_FUEL_LVL_DIG_K_R2,
       SID_FUEL_LVL_DIG_K_L2,
       SID_FUEL_LVL_DIG_K_R3,
       SID_FUEL_LVL_DIG_K_L3,
       SID_FUEL_LVL_DIG_K_R4,
       SID_FUEL_LVL_DIG_K_L4,
       SID_FUEL_LVL_DIG_K_R5,
       SID_FUEL_LVL_DIG_K_L5,
       SID_FUEL_LVL_DIG_K_R6,
       SID_FUEL_LVL_DIG_K_L6,
       SID_FUEL_LVL_DIG_K_R7,
       SID_FUEL_LVL_DIG_K_L7,
       SID_FUEL_LVL_DIG_K_R8,
       SID_FUEL_LVL_DIG_K_L8,
       SID_FUEL_LVL_DIG_K_R9,
       SID_FUEL_LVL_DIG_K_L9,
       SID_FUEL_LVL_DIG_K_R10,
       SID_FUEL_LVL_DIG_K_L10,
       SID_FUEL_LVL_DIG_K_R11,
       SID_FUEL_LVL_DIG_K_L11,
       SID_FUEL_LVL_DIG_K_R12,
       SID_FUEL_LVL_DIG_K_L12,
       SID_FUEL_LVL_DIG_K_R13,
       SID_FUEL_LVL_DIG_K_L13,
       SID_FUEL_LVL_DIG_K_R14,
       SID_FUEL_LVL_DIG_K_L14,
       SID_FUEL_LVL_DIG_K_R15,
       SID_FUEL_LVL_DIG_K_L15,
       SID_FUEL_LVL_DIG_K_R16,
       SID_FUEL_LVL_DIG_K_L16,
       SID_FUEL_LVL_DIG_K_R17,
       SID_FUEL_LVL_DIG_K_L17,
       SID_FUEL_LVL_DIG_K_R18,
       SID_FUEL_LVL_DIG_K_L18,
       SID_FUEL_LVL_DIG_K_R19,
       SID_FUEL_LVL_DIG_K_L19,
       SID_FUEL_LVL_DIG_K_R20,
       SID_FUEL_LVL_DIG_K_L20,

       SID_ENG_TEMP_DIG_L_SENSOR_SELECTION,
       SID_ENG_TEMP_DIG_L_DIG_SOURCE,
       SID_ENG_TEMP_DIG_L_DIG_POLARITY,
       SID_ENG_TEMP_DIG_L_DIG_ACTION,
       SID_ENG_TEMP_DIG_L_DIG_ACTIVATION,
       SID_ENG_TEMP_DIG_L_DIG_ACTIVATION_DELAY,
       SID_ENG_TEMP_DIG_L_OPEN_CKT_WARNING,
       SID_ENG_TEMP_DIG_L_R1,
       SID_ENG_TEMP_DIG_L_T1,
       SID_ENG_TEMP_DIG_L_R2,
       SID_ENG_TEMP_DIG_L_T2,
       SID_ENG_TEMP_DIG_L_R3,
       SID_ENG_TEMP_DIG_L_T3,
       SID_ENG_TEMP_DIG_L_R4,
       SID_ENG_TEMP_DIG_L_T4,
       SID_ENG_TEMP_DIG_L_R5,
       SID_ENG_TEMP_DIG_L_T5,
       SID_ENG_TEMP_DIG_L_R6,
       SID_ENG_TEMP_DIG_L_T6,
       SID_ENG_TEMP_DIG_L_R7,
       SID_ENG_TEMP_DIG_L_T7,
       SID_ENG_TEMP_DIG_L_R8,
       SID_ENG_TEMP_DIG_L_T8,
       SID_ENG_TEMP_DIG_L_R9,
       SID_ENG_TEMP_DIG_L_T9,
       SID_ENG_TEMP_DIG_L_R10,
       SID_ENG_TEMP_DIG_L_T10,

       SID_SHEL_TEMP_DIG_M_SENSOR_SELECTION,
       SID_SHEL_TEMP_DIG_M_DIG_SOURCE,
       SID_SHEL_TEMP_DIG_M_DIG_POLARITY,
       SID_SHEL_TEMP_DIG_M_DIG_ACTION,
       SID_SHEL_TEMP_DIG_M_DIG_ACTIVATION,
       SID_SHEL_TEMP_DIG_M_DIG_ACTIVATION_DELAY,
       SID_SHEL_TEMP_DIG_M_HIGH_TEMP_THRESHOLD,
       SID_SHEL_TEMP_DIG_M_LOW_TEMP_THRESHOLD,
       SID_SHEL_TEMP_DIG_M_HIGH_TEMP_MON_DELAY,
       SID_SHEL_TEMP_DIG_M_DG_RUN_DURATION,
       SID_SHEL_TEMP_DIG_M_OPEN_CKT_NOTIFICATION,
       SID_SHEL_TEMP_DIG_M_R1,
       SID_SHEL_TEMP_DIG_M_T1,
       SID_SHEL_TEMP_DIG_M_R2,
       SID_SHEL_TEMP_DIG_M_T2,
       SID_SHEL_TEMP_DIG_M_R3,
       SID_SHEL_TEMP_DIG_M_T3,
       SID_SHEL_TEMP_DIG_M_R4,
       SID_SHEL_TEMP_DIG_M_T4,
       SID_SHEL_TEMP_DIG_M_R5,
       SID_SHEL_TEMP_DIG_M_T5,
       SID_SHEL_TEMP_DIG_M_R6,
       SID_SHEL_TEMP_DIG_M_T6,
       SID_SHEL_TEMP_DIG_M_R7,
       SID_SHEL_TEMP_DIG_M_T7,
       SID_SHEL_TEMP_DIG_M_R8,
       SID_SHEL_TEMP_DIG_M_T8,
       SID_SHEL_TEMP_DIG_M_R9,
       SID_SHEL_TEMP_DIG_M_T9,
       SID_SHEL_TEMP_DIG_M_R10,
       SID_SHEL_TEMP_DIG_M_T10,

       SID_AUX_S2_RES_DIG_N_SENSOR_SELECTION,
       SID_AUX_S2_RES_DIG_N_DIG_SOURCE,
       SID_AUX_S2_RES_DIG_N_DIG_POLARITY,
       SID_AUX_S2_RES_DIG_N_DIG_ACTION,
       SID_AUX_S2_RES_DIG_N_DIG_ACTIVATION,
       SID_AUX_S2_RES_DIG_N_DIG_ACTIVATION_DELAY,
       SID_AUX_S2_RES_DIG_N_ACTION,
       SID_AUX_S2_RES_DIG_N_THRESHOLD,
       SID_AUX_S2_RES_DIG_N_THRESHOLD_TYPE,
       SID_AUX_S2_RES_DIG_N_OPEN_CKT_WARNING,
       SID_AUX_S2_RES_DIG_N_R1,
       SID_AUX_S2_RES_DIG_N_V1,
       SID_AUX_S2_RES_DIG_N_R2,
       SID_AUX_S2_RES_DIG_N_V2,
       SID_AUX_S2_RES_DIG_N_R3,
       SID_AUX_S2_RES_DIG_N_V3,
       SID_AUX_S2_RES_DIG_N_R4,
       SID_AUX_S2_RES_DIG_N_V4,
       SID_AUX_S2_RES_DIG_N_R5,
       SID_AUX_S2_RES_DIG_N_V5,
       SID_AUX_S2_RES_DIG_N_R6,
       SID_AUX_S2_RES_DIG_N_V6,
       SID_AUX_S2_RES_DIG_N_R7,
       SID_AUX_S2_RES_DIG_N_V7,
       SID_AUX_S2_RES_DIG_N_R8,
       SID_AUX_S2_RES_DIG_N_V8,
       SID_AUX_S2_RES_DIG_N_R9,
       SID_AUX_S2_RES_DIG_N_V9,
       SID_AUX_S2_RES_DIG_N_R10,
       SID_AUX_S2_RES_DIG_N_V10,

       SID_AUX_S3_DIG_O_SENSOR_SELECTION,
       SID_AUX_S3_DIG_O_DIG_SOURCE,
       SID_AUX_S3_DIG_O_DIG_POLARITY,
       SID_AUX_S3_DIG_O_DIG_ACTION,
       SID_AUX_S3_DIG_O_DIG_ACTIVATION,
       SID_AUX_S3_DIG_O_DIG_ACTIVATION_DELAY,
       SID_AUX_S3_DIG_O_CIRCUIT_FAULT_ACTION,
       SID_AUX_S3_DIG_O_I1_V1,
       SID_AUX_S3_DIG_O_P1,
       SID_AUX_S3_DIG_O_I2_V2,
       SID_AUX_S3_DIG_O_P2,
       SID_AUX_S3_DIG_O_I3_V3,
       SID_AUX_S3_DIG_O_P3,
       SID_AUX_S3_DIG_O_I4_V4,
       SID_AUX_S3_DIG_O_P4,
       SID_AUX_S3_DIG_O_I5_V5,
       SID_AUX_S3_DIG_O_P5,
       SID_AUX_S3_DIG_O_I6_V6,
       SID_AUX_S3_DIG_O_P6,
       SID_AUX_S3_DIG_O_I7_V7,
       SID_AUX_S3_DIG_O_P7,
       SID_AUX_S3_DIG_O_I8_V8,
       SID_AUX_S3_DIG_O_P8,
       SID_AUX_S3_DIG_O_I9_V9,
       SID_AUX_S3_DIG_O_P9,
       SID_AUX_S3_DIG_O_I10_V10,
       SID_AUX_S3_DIG_O_P10,

       SID_AUX_S4_DIG_P_SENSOR_SELECTION,
       SID_AUX_S4_DIG_P_DIG_SOURCE,
       SID_AUX_S4_DIG_P_DIG_POLARITY,
       SID_AUX_S4_DIG_P_DIG_ACTION,
       SID_AUX_S4_DIG_P_DIG_ACTIVATION,
       SID_AUX_S4_DIG_P_DIG_ACTIVATION_DELAY,
       SID_AUX_S4_DIG_P_SHUTDOWN,
       SID_AUX_S4_DIG_P_SHUTDOWN_THRESHOLD,
       SID_AUX_S4_DIG_P_NOTIFICATION,
       SID_AUX_S4_DIG_P_NOTIFICATION_THRESHOLD,
       SID_AUX_S4_DIG_P_FUEL_THEFT_WARNING,
       SID_AUX_S4_DIG_P_FUEL_THEFT_THRESHOLD,
       SID_AUX_S4_DIG_P_FUEL_CONSUMPTION,
       SID_AUX_S4_DIG_P_FUEL_IN_PCT,
       SID_AUX_S4_DIG_P_SENSOR_LOW_VTG,
       SID_AUX_S4_DIG_P_SENSOR_HIGH_VTG,
       SID_AUX_S4_DIG_P_TANK_WITH_STEP,
       SID_AUX_S4_DIG_P_TANK_WIDTH,
       SID_AUX_S4_DIG_P_TANK_LENGTH_1,
       SID_AUX_S4_DIG_P_TANK_HEIGHT_1,
       SID_AUX_S4_DIG_P_TANK_LENGTH_2,
       SID_AUX_S4_DIG_P_TANK_HEIGHT_2,

       SID_DIG_IN_Q_SOURCE,
       SID_DIG_IN_Q_POLARITY,
       SID_DIG_IN_Q_ACTION,
       SID_DIG_IN_Q_ACTIVATION,
       SID_DIG_IN_Q_ACTIVATION_DELAY,

       SID_DIG_IN_R_SOURCE,
       SID_DIG_IN_R_POLARITY,
       SID_DIG_IN_R_ACTION,
       SID_DIG_IN_R_ACTIVATION,
       SID_DIG_IN_R_ACTIVATION_DELAY,

       SID_OUT_A_SOURCE,
       SID_OUT_A_ON_ACTIVATION,
       SID_OUT_B_SOURCE,
       SID_OUT_B_ON_ACTIVATION,
       SID_OUT_C_SOURCE,
       SID_OUT_C_ON_ACTIVATION,
       SID_OUT_D_SOURCE,
       SID_OUT_D_ON_ACTIVATION,
       SID_OUT_E_SOURCE,
       SID_OUT_E_ON_ACTIVATION,
       SID_OUT_F_SOURCE,
       SID_OUT_F_ON_ACTIVATION,
       SID_OUT_G_SOURCE,
       SID_OUT_G_ON_ACTIVATION,
       SID_OUT_H_SOURCE,
       SID_OUT_H_ON_ACTIVATION,
       SID_OUT_I_SOURCE,
       SID_OUT_I_ON_ACTIVATION,

       SID_CRANKING_TIMER_CRANK_HOLD_TIME,
       SID_CRANKING_TIMER_CRANK_REST_TIME,
       SID_CRANKING_TIMER_MANUAL_START_DELAY,
       SID_CRANKING_TIMER_AUTO_START_DELAY,

       SID_GENERAL_TIMER_SAFETY_MONITOR_DELAY,
       SID_GENERAL_TIMER_MAINS_DETECT_DELAY,
       SID_GENERAL_TIMER_ALT_DETECT_DELAY,
       SID_GENERAL_TIMER_WARM_UP_DELAY,
       SID_GENERAL_TIMER_RETN_TO_MAINS_DELAY,
       SID_GENERAL_TIMER_ENG_COOL_TIME,
       SID_GENERAL_TIMER_STOP_ACTION_TIME,
       SID_GENERAL_TIMER_ADDN_STOPPING_TIME,
       SID_GENERAL_TIMER_LOAD_TRANSFER_DELAY,
       SID_GENERAL_TIMER_PWR_SAVE_MODE_DELAY,
       SID_GENERAL_TIMER_SCRN_CHNGOVER_TIME,
       SID_GENERAL_TIMER_SOUNDER_ALARM_TIMER,
       SID_GENERAL_TIMER_TEST_MODE_TIMER,

       SID_ALT_CONFIG_ALT_PRESENT,
       SID_ALT_CONFIG_NUMBER_OF_POLES,
       SID_ALT_CONFIG_ALT_AC_SYSTEM,
       SID_ALT_CONFIG_MIN_HEALTHY_VOLT,
       SID_ALT_CONFIG_MIN_HEALTHY_FREQ,
       SID_ALT_CONFIG_PHASE_REVERSAL_DETECT,
       SID_ALT_CONFIG_PHASE_REVERSAL_ACTION,
       SID_ALT_CONFIG_AUTO_LOAD_TRANSFER,
       SID_ALT_CONFIG_ALT_WAVE_DETECTION,

       SID_VOLT_MONITOR_UNDER_VOLT_SHUTDOWN,
       SID_VOLT_MONITOR_UV_SHUTDOWN_THRESHOLD,
       SID_VOLT_MONITOR_UNDER_VOLT_WARNING,
       SID_VOLT_MONITOR_UV_WARNING_THRESHOLD,
       SID_VOLT_MONITOR_OVER_VOLT_SHUTDOWN,
       SID_VOLT_MONITOR_OV_SHUTDOWN_THRESHOLD,
       SID_VOLT_MONITOR_OVER_VOLT_WARNING,
       SID_VOLT_MONITOR_OV_WARNING_THRESHOLD,

       SID_FREQ_MONITOR_UNDER_FREQ_SHUTDOWN,
       SID_FREQ_MONITOR_UF_SHUTDOWN_THRESHOLD,
       SID_FREQ_MONITOR_UNDER_FREQ_WARNING,
       SID_FREQ_MONITOR_UF_WARNING_THRESHOLD,
       SID_FREQ_MONITOR_OVER_FREQ_SHUTDOWN,
       SID_FREQ_MONITOR_OF_SHUTDOWN_THRESHOLD,
       SID_FREQ_MONITOR_OVER_FREQ_WARNING,
       SID_FREQ_MONITOR_OF_WARNING_THRESHOLD,

       SID_CURRENT_MONITOR_LOAD_CT_RATIO,
       SID_CURRENT_MONITOR_OVER_CURR_ACTION,
       SID_CURRENT_MONITOR_OVER_CURR_THRESHOLD,
       SID_CURRENT_MONITOR_OVER_CURR_DELAY,
       SID_CURRENT_MONITOR_CT_CORRECTION_FACTOR,
       SID_CURRENT_MONITOR_CT_LOCATION,

       SID_FAN_CURR_MONITOR_FAN_CURRENT_MON,
       SID_FAN_CURR_MONITOR_FAN_MON_CT_RATIO,
       SID_FAN_CURR_MONITOR_HIGH_CURR_THRESHOLD,
       SID_FAN_CURR_MONITOR_HIGH_CURR_ACTION,
       SID_FAN_CURR_MONITOR_LOW_CURR_THRESHOLD,
       SID_FAN_CURR_MONITOR_LOW_CURR_ACTION,
       SID_FAN_CURR_MONITOR_CURR_MON_DELAY,

       SID_LOAD_MONITOR_GEN_RATING,
       SID_LOAD_MONITOR_FULL_LOAD_CURRENT,
       SID_LOAD_MONITOR_OVERLOAD_ACTION,
       SID_LOAD_MONITOR_OVERLOAD_THRESHOLD,
       SID_LOAD_MONITOR_OVERLOAD_MON_DELAY,
       SID_LOAD_MONITOR_UNBAL_LOAD_ACTION,
       SID_LOAD_MONITOR_UNBAL_LOAD_THRESHOLD,
       SID_LOAD_MONITOR_UNBAL_LOAD_DELAY,
       SID_LOAD_MONITOR_UNBAL_LOAD_ACT_THRESH,

       SID_MAINS_CONFIG_MAINS_MONITORING,
       SID_MAINS_CONFIG_MAINS_AC_SYSTEM,
       SID_MAINS_CONFIG_PHASE_REVERSAL_DETECT,
       SID_MAINS_CONFIG_PHASE_REVERSAL_ACTION,
       SID_MAINS_CONFIG_3PH_CALC_EN_FOR_1PH,
       SID_UNDER_VOLT_MON_ENABLE,
       SID_UNDER_VOLT_MON_TRIP,
       SID_UNDER_VOLT_MON_RETURN,
       SID_OVER_VOLT_MON_ENABLE,
       SID_OVER_VOLT_MON_TRIP,
       SID_OVER_VOLT_MON_RETURN,
       SID_UNDER_FREQ_MON_ENABLE,
       SID_UNDER_FREQ_MON_TRIP,
       SID_UNDER_FREQ_MON_RETURN,
       SID_OVER_FREQ_MON_ENABLE,
       SID_OVER_FREQ_MON_TRIP,
       SID_OVER_FREQ_MON_RETURN,

       SID_CRANK_DISCONN_START_ATTEMPTS,
       SID_CRANK_DISCONN_DISCONN_ON_LOP_SENS,
       SID_CRANK_DISCONN_DISCONN_LOP_SENS,
       SID_CRANK_DISCONN_MON_LLOP_BEFORE_CRNK,
       SID_CRANK_DISCONN_MON_LOP_BEFORE_CRANK,
       SID_CRANK_DISCONN_DISCONN_ON_LLOP_SW,
       SID_CRANK_DISCONN_LLOP_SW_TRANS_TIME,
       SID_CRANK_DISCONN_ALT_FREQUENCY,
       SID_CRANK_DISCONN_ENGINE_SPEED,
       SID_CRANK_DISCONN_DISCONN_ON_CHG_ALT_VOLT,
       SID_CRANK_DISCONN_CHG_ALT_THRESHOLD,
       SID_SPEED_MONITOR_SPEED_SENSE_SOURCE,
       /*SID_SPEED_MONITOR_RESERVED,*/
       SID_SPEED_MONITOR_UNDER_SPEED_SHUTDOWN,
       SID_SPEED_MONITOR_UNDER_SPEED_THRESHOLD,
       SID_SPEED_MONITOR_UNDER_SPEED_DELAY,
       SID_SPEED_MONITOR_OVER_SPEED_THRESHOLD,
       SID_SPEED_MONITOR_OVER_SPEED_DELAY,
       SID_SPEED_MONITOR_GROSS_OS_THRESHOLD,
       SID_BATTERY_MONITOR_LOW_VOLT_ACTION,
       SID_BATTERY_MONITOR_LOW_VOLT_THRESHOLD,
       SID_BATTERY_MONITOR_LOW_VOLT_DELAY,
       SID_BATTERY_MONITOR_HIGH_VOLT_ACTION,
       SID_BATTERY_MONITOR_HIGH_VOLT_THRESHOLD,
       SID_BATTERY_MONITOR_HIGH_VOLT_DELAY,
       SID_CHARGE_ALT_MON_FAIL_ACTION,
       SID_CHARGE_ALT_MON_FAIL_THRESHOLD,
       SID_CHARGE_ALT_MON_FAIL_DELAY,
       SID_PREHEAT_PREHEAT_TIMER,
       SID_PREHEAT_ENG_TEMPERATURE,
       SID_PREHEAT_ENG_TEMP_THRESHOLD,
       SID_PREHEAT_AMB_TEMPERATURE,


       SID_ENGINE_TYPE,
       SID_ENG_SPEED_FROM_ECU,
       SID_LOP_FROM_ECU,
       SID_CLNT_TEMP_FROM_ECU,
       SID_ENG_RUN_HOURS_FROM_ECU,
       SID_BAT_VTG_FROM_ECU,
       SID_OIL_TEMP_FROM_ECU,
       SID_COMM_FAIL_ACTION,
       SID_COMM_FAIL_ACTIVATION,
       SID_COMM_FAIL_ACT_DELAY,
       SID_AMBER_FAIL_ACTION,
       SID_AMBER_FAIL_ACTIVATION,
       SID_AMBER_FAIL_ACT_DELAY,
       SID_RED_FAIL_ACTION,
       SID_RED_FAIL_ACTIVATION,
       SID_RED_FAIL_ACT_DELAY,
       SID_MALFUNC_FAIL_ACTION,
       SID_MALFUNC_FAIL_ACTIVATION,
       SID_MALFUNC_FAIL_ACT_DELAY,
       SID_PROTECT_FAIL_ACTION,
       SID_PROTECT_FAIL_ACTIVATION,
       SID_PROTECT_FAIL_ACT_DELAY,       
       SID_SGC_SOURCE_ADDR,
       SID_ECU_SOURCE_ADDR,
       SID_LOP_SENS_ECU_SHUTDOWN,
       SID_LOP_SENS_ECU_SHUTDOWN_THRESH,
       SID_LOP_SENS_ECU_WARNING,
       SID_LOP_SENS_ECU_WARNING_THRESH,
       SID_CLNT_TEMP_SHUTDOWN_THRESH,
       SID_CLNT_TEMP_SHUTDOWN_EN,
       SID_CLNT_TEMP_WARNING_THRESH,
       SID_CLNT_TEMP_WARNING_EN,
       SID_OIL_TEMP_SHUTDOWN_EN,
       SID_OIL_TEMP_SHUTDOWN_THRESH,
       SID_OIL_TEMP_WARNING_EN,
       SID_OIL_TEMP_WARNING_THRESH,

       SID_ENABLE_EGR_TIMERS,
       SID_FAULT_SHUTDOWN_TIMER,
       SID_FAULT_WARNING_TIMER,
       SID_HEAL_TIMER,

       SID_MAINT_ALARM_ACTION,
       SID_MAINT_ALARM_DUE_AT_ENGINE_HOURS,
       SID_ALARM_DUE_DATE_SERVICE_DATE_1,
       SID_ALARM_DUE_DATE_SERVICE_DATE_2,
       SID_ALARM_DUE_DATE_SERVICE_DATE_3,

       SID_PROFILE_NAME,

       SID_LEAF_NODE_STRING
   };

   //Main Menus
   enum
   {
       ID_MODULE_S,
       ID_INPUTS_S,
       ID_OUTPUTS_S,
       ID_TIMERS_S,
       ID_GENERATOR_S,
       ID_MAINS_S,
       ID_ENGINE_S,
       ID_MAINTENANCE_S,
       ID_PASSWORD,
       ID_SELECT_PROFILE_MENU,
       ID_MAIN_MENU_LAST
   };

   //Sub menus
   enum
   {
       /*Module*/
       ID_GENERAL_S,
       ID_DISPLAY_S,
       ID_MODBUS_COMM,
       ID_BTS_CONFIG,
       ID_CYCLIC_CONFIG_S,
       ID_NIGHT_MODE_CONFG,
       ID_AUTO_MD_SWITCH,
       /*Inputs*/
       ID_DIG_IN_A_S,
       ID_DIG_IN_B_S,
       ID_DIG_IN_C_S,
       ID_DIG_IN_D_S,
       ID_DIG_IN_E_S,
       ID_DIG_IN_F_S,
       ID_DIG_IN_G_S,
       ID_DIG_IN_H_S,
       ID_DIG_IN_I_S,
       ID_LOP_RES_DIG_J,
       ID_FUEL_LVL_DIG_K,
       ID_ENG_TEMP_DIG_L,
       ID_SHEL_TEMP_DIG_M,
       ID_AUX_S2_RES_DIG_N,
       ID_AUX_S3_DIG_O_S,
       ID_AUX_S4_DIG_P_S,
       ID_DIG_IN_Q_S,
       ID_DIG_IN_R_S,
       /*Outputs*/
       ID_OUT_A_S,
       ID_OUT_B_S,
       ID_OUT_C_S,
       ID_OUT_D_S,
       ID_OUT_E_S,
       ID_OUT_F_S,
       ID_OUT_G_S,
       ID_OUT_H_S,
       ID_OUT_I_S,
       /*Timer*/
       ID_CRANKING_TIMER_S,
       ID_GENERAL_TIMER_S,
       /*Generator*/
       ID_ALT_CONFIG_S,
       ID_VOLT_MONITOR_S,
       ID_FREQ_MONITOR_S,
       ID_CURRENT_MONITOR_S,
       ID_FAN_CURR_MONITOR,
       ID_LOAD_MONITOR_S,
       /*Mains*/
       ID_MAINS_CONFIG_S,
       ID_UNDER_VOLT_MON,
       ID_OVER_VOLT_MON,
       ID_UNDER_FREQ_MON,
       ID_OVER_FREQ_MON,
       /*Engine*/
       ID_CRANK_DISCONN,
       ID_SPEED_MONITOR_S,
       ID_BATTERY_MONITOR_S,
       ID_CHARGE_ALT_MON_S,
       ID_PREHEAT_S,

       ID_ECU,
       ID_LUBE_OIL_PRESSURE,
       ID_ENG_TEMPERATURE,
       ID_LUBE_OIL_TEMPERATURE,

       /*EGR Timers*/
       ID_EGR_TIMERS,
       /*Maintenance*/
       ID_MAINT_ALARM_S,
       ID_ALARM_DUE_DATE_S,
       /*ID*/
       ID_ENG_SR_NO,
       ID_PASSWORD_1,
       ID_PASSWORD_2,
       /*Slect Profile*/
       ID_SELECT_PROFILE,

       ID_SUB_MENU_LAST
   };

enum
{
    /*Module*/
    INDEX_OF_GENERAL_PROFILE_NAME,
    INDEX_OF_GENERAL_POWER_ON_MODE,
    INDEX_OF_GENERAL_POWER_ON_LAMP_TEST,
    INDEX_OF_GENERAL_PASSWORD_LOCK,

    INDEX_OF_DISPLAY_CONTRAST,
    INDEX_OF_DISPLAY_POWER_SAVE_MODE,

    INDEX_OF_MODBUS_COMM_COMM_MODE,
    INDEX_OF_MODBUS_COMM_MODBUS_SLAVE_ID,
    INDEX_OF_MODBUS_COMM_MODBUS_BAUDRATE,
    INDEX_OF_MODBUS_COMM_PARITY,

    INDEX_OF_BTS_CONFIG_BATTERY_MON,
    INDEX_OF_BTS_CONFIG_LOW_BATT_THRESHOLD,
    INDEX_OF_BTS_CONFIG_LOW_BATT_MON_DELAY,
    INDEX_OF_BTS_CONFIG_DG_RUN_DURATION,

    INDEX_OF_CYCLIC_CONFIG_CYCLIC_MODE,
    INDEX_OF_CYCLIC_CONFIG_DG_OFF_DURATION,
    INDEX_OF_CYCLIC_CONFIG_DG_ON_DURATION,

    INDEX_OF_NIGHT_MODE_CONFG_NIGHT_MODE,
    INDEX_OF_NIGHT_MODE_CONFG_START_TIME,
    INDEX_OF_NIGHT_MODE_CONFG_OFF_DURATION,

    INDEX_OF_AUTO_MD_SWITCH_AUTO_MD_SWITCH,
    INDEX_OF_AUTO_MD_SWITCH_MANUAL_MODE_TIME,
    INDEX_OF_AUTO_MD_SWITCH_OUTPUT_ON_TIME,
    /*Inputs menu*/
    INDEX_OF_DIG_IN_A_SOURCE,
    INDEX_OF_DIG_IN_A_POLARITY,
    INDEX_OF_DIG_IN_A_ACTION,
    INDEX_OF_DIG_IN_A_ACTIVATION,
    INDEX_OF_DIG_IN_A_ACTIVATION_DELAY,

    INDEX_OF_DIG_IN_B_SOURCE,
    INDEX_OF_DIG_IN_B_POLARITY,
    INDEX_OF_DIG_IN_B_ACTION,
    INDEX_OF_DIG_IN_B_ACTIVATION,
    INDEX_OF_DIG_IN_B_ACTIVATION_DELAY,

    INDEX_OF_DIG_IN_C_SOURCE,
    INDEX_OF_DIG_IN_C_POLARITY,
    INDEX_OF_DIG_IN_C_ACTION,
    INDEX_OF_DIG_IN_C_ACTIVATION,
    INDEX_OF_DIG_IN_C_ACTIVATION_DELAY,

    INDEX_OF_DIG_IN_D_SOURCE,
    INDEX_OF_DIG_IN_D_POLARITY,
    INDEX_OF_DIG_IN_D_ACTION,
    INDEX_OF_DIG_IN_D_ACTIVATION,
    INDEX_OF_DIG_IN_D_ACTIVATION_DELAY,

    INDEX_OF_DIG_IN_E_SOURCE,
    INDEX_OF_DIG_IN_E_POLARITY,
    INDEX_OF_DIG_IN_E_ACTION,
    INDEX_OF_DIG_IN_E_ACTIVATION,
    INDEX_OF_DIG_IN_E_ACTIVATION_DELAY,

    INDEX_OF_DIG_IN_F_SOURCE,
    INDEX_OF_DIG_IN_F_POLARITY,
    INDEX_OF_DIG_IN_F_ACTION,
    INDEX_OF_DIG_IN_F_ACTIVATION,
    INDEX_OF_DIG_IN_F_ACTIVATION_DELAY,

    INDEX_OF_DIG_IN_G_SOURCE,
    INDEX_OF_DIG_IN_G_POLARITY,
    INDEX_OF_DIG_IN_G_ACTION,
    INDEX_OF_DIG_IN_G_ACTIVATION,
    INDEX_OF_DIG_IN_G_ACTIVATION_DELAY,

    INDEX_OF_DIG_IN_H_SOURCE,
    INDEX_OF_DIG_IN_H_POLARITY,
    INDEX_OF_DIG_IN_H_ACTION,
    INDEX_OF_DIG_IN_H_ACTIVATION,
    INDEX_OF_DIG_IN_H_ACTIVATION_DELAY,

    INDEX_OF_DIG_IN_I_SOURCE,
    INDEX_OF_DIG_IN_I_POLARITY,
    INDEX_OF_DIG_IN_I_ACTION,
    INDEX_OF_DIG_IN_I_ACTIVATION,
    INDEX_OF_DIG_IN_I_ACTIVATION_DELAY,

    INDEX_OF_LOP_RES_DIG_J_SENSOR_SELECTION,
    INDEX_OF_LOP_RES_DIG_J_DIG_SOURCE,
    INDEX_OF_LOP_RES_DIG_J_DIG_POLARITY,
    INDEX_OF_LOP_RES_DIG_J_DIG_ACTION,
    INDEX_OF_LOP_RES_DIG_J_DIG_ACTIVATION,
    INDEX_OF_LOP_RES_DIG_J_DIG_ACTIVATION_DELAY,
    INDEX_OF_LOP_RES_DIG_J_CIRCUIT_FAULT_ACTION,
    INDEX_OF_LOP_RES_DIG_J_R1,
    INDEX_OF_LOP_RES_DIG_J_V1,
    INDEX_OF_LOP_RES_DIG_J_R2,
    INDEX_OF_LOP_RES_DIG_J_V2,
    INDEX_OF_LOP_RES_DIG_J_R3,
    INDEX_OF_LOP_RES_DIG_J_V3,
    INDEX_OF_LOP_RES_DIG_J_R4,
    INDEX_OF_LOP_RES_DIG_J_V4,
    INDEX_OF_LOP_RES_DIG_J_R5,
    INDEX_OF_LOP_RES_DIG_J_V5,
    INDEX_OF_LOP_RES_DIG_J_R6,
    INDEX_OF_LOP_RES_DIG_J_V6,
    INDEX_OF_LOP_RES_DIG_J_R7,
    INDEX_OF_LOP_RES_DIG_J_V7,
    INDEX_OF_LOP_RES_DIG_J_R8,
    INDEX_OF_LOP_RES_DIG_J_V8,
    INDEX_OF_LOP_RES_DIG_J_R9,
    INDEX_OF_LOP_RES_DIG_J_V9,
    INDEX_OF_LOP_RES_DIG_J_R10,
    INDEX_OF_LOP_RES_DIG_J_V10,

    INDEX_OF_FUEL_LVL_DIG_K_SENSOR_SELECTION,
    INDEX_OF_FUEL_LVL_DIG_K_DIG_SOURCE,
    INDEX_OF_FUEL_LVL_DIG_K_DIG_POLARITY,
    INDEX_OF_FUEL_LVL_DIG_K_DIG_ACTION,
    INDEX_OF_FUEL_LVL_DIG_K_DIG_ACTIVATION,
    INDEX_OF_FUEL_LVL_DIG_K_DIG_ACTIVATION_DELAY,
    INDEX_OF_FUEL_LVL_DIG_K_SHUTDOWN,
    INDEX_OF_FUEL_LVL_DIG_K_SHUTDOWN_THRESHOLD,
    INDEX_OF_FUEL_LVL_DIG_K_NOTIFICATION,
    INDEX_OF_FUEL_LVL_DIG_K_NOTIFICATION_THRESHOLD,
    INDEX_OF_FUEL_LVL_DIG_K_FUEL_TANK_CAPACITY,
    INDEX_OF_FUEL_LVL_DIG_K_FUEL_THEFT_WARNING,
    INDEX_OF_FUEL_LVL_DIG_K_FUEL_THEFT_THRESHOLD,
    INDEX_OF_FUEL_LVL_DIG_K_FUEL_CONSUMPTION,
    INDEX_OF_FUEL_LVL_DIG_K_FUEL_IN_PCT,
    INDEX_OF_FUEL_LVL_DIG_K_R1,
    INDEX_OF_FUEL_LVL_DIG_K_L1,
    INDEX_OF_FUEL_LVL_DIG_K_R2,
    INDEX_OF_FUEL_LVL_DIG_K_L2,
    INDEX_OF_FUEL_LVL_DIG_K_R3,
    INDEX_OF_FUEL_LVL_DIG_K_L3,
    INDEX_OF_FUEL_LVL_DIG_K_R4,
    INDEX_OF_FUEL_LVL_DIG_K_L4,
    INDEX_OF_FUEL_LVL_DIG_K_R5,
    INDEX_OF_FUEL_LVL_DIG_K_L5,
    INDEX_OF_FUEL_LVL_DIG_K_R6,
    INDEX_OF_FUEL_LVL_DIG_K_L6,
    INDEX_OF_FUEL_LVL_DIG_K_R7,
    INDEX_OF_FUEL_LVL_DIG_K_L7,
    INDEX_OF_FUEL_LVL_DIG_K_R8,
    INDEX_OF_FUEL_LVL_DIG_K_L8,
    INDEX_OF_FUEL_LVL_DIG_K_R9,
    INDEX_OF_FUEL_LVL_DIG_K_L9,
    INDEX_OF_FUEL_LVL_DIG_K_R10,
    INDEX_OF_FUEL_LVL_DIG_K_L10,
    INDEX_OF_FUEL_LVL_DIG_K_R11,
    INDEX_OF_FUEL_LVL_DIG_K_L11,
    INDEX_OF_FUEL_LVL_DIG_K_R12,
    INDEX_OF_FUEL_LVL_DIG_K_L12,
    INDEX_OF_FUEL_LVL_DIG_K_R13,
    INDEX_OF_FUEL_LVL_DIG_K_L13,
    INDEX_OF_FUEL_LVL_DIG_K_R14,
    INDEX_OF_FUEL_LVL_DIG_K_L14,
    INDEX_OF_FUEL_LVL_DIG_K_R15,
    INDEX_OF_FUEL_LVL_DIG_K_L15,
    INDEX_OF_FUEL_LVL_DIG_K_R16,
    INDEX_OF_FUEL_LVL_DIG_K_L16,
    INDEX_OF_FUEL_LVL_DIG_K_R17,
    INDEX_OF_FUEL_LVL_DIG_K_L17,
    INDEX_OF_FUEL_LVL_DIG_K_R18,
    INDEX_OF_FUEL_LVL_DIG_K_L18,
    INDEX_OF_FUEL_LVL_DIG_K_R19,
    INDEX_OF_FUEL_LVL_DIG_K_L19,
    INDEX_OF_FUEL_LVL_DIG_K_R20,
    INDEX_OF_FUEL_LVL_DIG_K_L20,

    INDEX_OF_ENG_TEMP_DIG_L_SENSOR_SELECTION,
    INDEX_OF_ENG_TEMP_DIG_L_DIG_SOURCE,
    INDEX_OF_ENG_TEMP_DIG_L_DIG_POLARITY,
    INDEX_OF_ENG_TEMP_DIG_L_DIG_ACTION,
    INDEX_OF_ENG_TEMP_DIG_L_DIG_ACTIVATION,
    INDEX_OF_ENG_TEMP_DIG_L_DIG_ACTIVATION_DELAY,
    INDEX_OF_ENG_TEMP_DIG_L_OPEN_CKT_WARNING,
    INDEX_OF_ENG_TEMP_DIG_L_R1,
    INDEX_OF_ENG_TEMP_DIG_L_T1,
    INDEX_OF_ENG_TEMP_DIG_L_R2,
    INDEX_OF_ENG_TEMP_DIG_L_T2,
    INDEX_OF_ENG_TEMP_DIG_L_R3,
    INDEX_OF_ENG_TEMP_DIG_L_T3,
    INDEX_OF_ENG_TEMP_DIG_L_R4,
    INDEX_OF_ENG_TEMP_DIG_L_T4,
    INDEX_OF_ENG_TEMP_DIG_L_R5,
    INDEX_OF_ENG_TEMP_DIG_L_T5,
    INDEX_OF_ENG_TEMP_DIG_L_R6,
    INDEX_OF_ENG_TEMP_DIG_L_T6,
    INDEX_OF_ENG_TEMP_DIG_L_R7,
    INDEX_OF_ENG_TEMP_DIG_L_T7,
    INDEX_OF_ENG_TEMP_DIG_L_R8,
    INDEX_OF_ENG_TEMP_DIG_L_T8,
    INDEX_OF_ENG_TEMP_DIG_L_R9,
    INDEX_OF_ENG_TEMP_DIG_L_T9,
    INDEX_OF_ENG_TEMP_DIG_L_R10,
    INDEX_OF_ENG_TEMP_DIG_L_T10,

    INDEX_OF_SHEL_TEMP_DIG_M_SENSOR_SELECTION,
    INDEX_OF_SHEL_TEMP_DIG_M_DIG_SOURCE,
    INDEX_OF_SHEL_TEMP_DIG_M_DIG_POLARITY,
    INDEX_OF_SHEL_TEMP_DIG_M_DIG_ACTION,
    INDEX_OF_SHEL_TEMP_DIG_M_DIG_ACTIVATION,
    INDEX_OF_SHEL_TEMP_DIG_M_DIG_ACTIVATION_DELAY,
    INDEX_OF_SHEL_TEMP_DIG_M_HIGH_TEMP_THRESHOLD,
    INDEX_OF_SHEL_TEMP_DIG_M_LOW_TEMP_THRESHOLD,
    INDEX_OF_SHEL_TEMP_DIG_M_HIGH_TEMP_MON_DELAY,
    INDEX_OF_SHEL_TEMP_DIG_M_DG_RUN_DURATION,
    INDEX_OF_SHEL_TEMP_DIG_M_OPEN_CKT_NOTIFICATION,
    INDEX_OF_SHEL_TEMP_DIG_M_R1,
    INDEX_OF_SHEL_TEMP_DIG_M_T1,
    INDEX_OF_SHEL_TEMP_DIG_M_R2,
    INDEX_OF_SHEL_TEMP_DIG_M_T2,
    INDEX_OF_SHEL_TEMP_DIG_M_R3,
    INDEX_OF_SHEL_TEMP_DIG_M_T3,
    INDEX_OF_SHEL_TEMP_DIG_M_R4,
    INDEX_OF_SHEL_TEMP_DIG_M_T4,
    INDEX_OF_SHEL_TEMP_DIG_M_R5,
    INDEX_OF_SHEL_TEMP_DIG_M_T5,
    INDEX_OF_SHEL_TEMP_DIG_M_R6,
    INDEX_OF_SHEL_TEMP_DIG_M_T6,
    INDEX_OF_SHEL_TEMP_DIG_M_R7,
    INDEX_OF_SHEL_TEMP_DIG_M_T7,
    INDEX_OF_SHEL_TEMP_DIG_M_R8,
    INDEX_OF_SHEL_TEMP_DIG_M_T8,
    INDEX_OF_SHEL_TEMP_DIG_M_R9,
    INDEX_OF_SHEL_TEMP_DIG_M_T9,
    INDEX_OF_SHEL_TEMP_DIG_M_R10,
    INDEX_OF_SHEL_TEMP_DIG_M_T10,

    INDEX_OF_AUX_S2_RES_DIG_N_SENSOR_SELECTION,
    INDEX_OF_AUX_S2_RES_DIG_N_DIG_SOURCE,
    INDEX_OF_AUX_S2_RES_DIG_N_DIG_POLARITY,
    INDEX_OF_AUX_S2_RES_DIG_N_DIG_ACTION,
    INDEX_OF_AUX_S2_RES_DIG_N_DIG_ACTIVATION,
    INDEX_OF_AUX_S2_RES_DIG_N_DIG_ACTIVATION_DELAY,
    INDEX_OF_AUX_S2_RES_DIG_N_ACTION,
    INDEX_OF_AUX_S2_RES_DIG_N_THRESHOLD,
    INDEX_OF_AUX_S2_RES_DIG_N_THRESHOLD_TYPE,
    INDEX_OF_AUX_S2_RES_DIG_N_OPEN_CKT_WARNING,
    INDEX_OF_AUX_S2_RES_DIG_N_R1,
    INDEX_OF_AUX_S2_RES_DIG_N_V1,
    INDEX_OF_AUX_S2_RES_DIG_N_R2,
    INDEX_OF_AUX_S2_RES_DIG_N_V2,
    INDEX_OF_AUX_S2_RES_DIG_N_R3,
    INDEX_OF_AUX_S2_RES_DIG_N_V3,
    INDEX_OF_AUX_S2_RES_DIG_N_R4,
    INDEX_OF_AUX_S2_RES_DIG_N_V4,
    INDEX_OF_AUX_S2_RES_DIG_N_R5,
    INDEX_OF_AUX_S2_RES_DIG_N_V5,
    INDEX_OF_AUX_S2_RES_DIG_N_R6,
    INDEX_OF_AUX_S2_RES_DIG_N_V6,
    INDEX_OF_AUX_S2_RES_DIG_N_R7,
    INDEX_OF_AUX_S2_RES_DIG_N_V7,
    INDEX_OF_AUX_S2_RES_DIG_N_R8,
    INDEX_OF_AUX_S2_RES_DIG_N_V8,
    INDEX_OF_AUX_S2_RES_DIG_N_R9,
    INDEX_OF_AUX_S2_RES_DIG_N_V9,
    INDEX_OF_AUX_S2_RES_DIG_N_R10,
    INDEX_OF_AUX_S2_RES_DIG_N_V10,

    INDEX_OF_AUX_S3_DIG_O_SENSOR_SELECTION,
    INDEX_OF_AUX_S3_DIG_O_DIG_SOURCE,
    INDEX_OF_AUX_S3_DIG_O_DIG_POLARITY,
    INDEX_OF_AUX_S3_DIG_O_DIG_ACTION,
    INDEX_OF_AUX_S3_DIG_O_DIG_ACTIVATION,
    INDEX_OF_AUX_S3_DIG_O_DIG_ACTIVATION_DELAY,
    INDEX_OF_AUX_S3_DIG_O_CIRCUIT_FAULT_ACTION,
    INDEX_OF_AUX_S3_DIG_O_I1_V1,
    INDEX_OF_AUX_S3_DIG_O_P1,
    INDEX_OF_AUX_S3_DIG_O_I2_V2,
    INDEX_OF_AUX_S3_DIG_O_P2,
    INDEX_OF_AUX_S3_DIG_O_I3_V3,
    INDEX_OF_AUX_S3_DIG_O_P3,
    INDEX_OF_AUX_S3_DIG_O_I4_V4,
    INDEX_OF_AUX_S3_DIG_O_P4,
    INDEX_OF_AUX_S3_DIG_O_I5_V5,
    INDEX_OF_AUX_S3_DIG_O_P5,
    INDEX_OF_AUX_S3_DIG_O_I6_V6,
    INDEX_OF_AUX_S3_DIG_O_P6,
    INDEX_OF_AUX_S3_DIG_O_I7_V7,
    INDEX_OF_AUX_S3_DIG_O_P7,
    INDEX_OF_AUX_S3_DIG_O_I8_V8,
    INDEX_OF_AUX_S3_DIG_O_P8,
    INDEX_OF_AUX_S3_DIG_O_I9_V9,
    INDEX_OF_AUX_S3_DIG_O_P9,
    INDEX_OF_AUX_S3_DIG_O_I10_V10,
    INDEX_OF_AUX_S3_DIG_O_P10,

    INDEX_OF_AUX_S4_DIG_P_SENSOR_SELECTION,
    INDEX_OF_AUX_S4_DIG_P_DIG_SOURCE,
    INDEX_OF_AUX_S4_DIG_P_DIG_POLARITY,
    INDEX_OF_AUX_S4_DIG_P_DIG_ACTION,
    INDEX_OF_AUX_S4_DIG_P_DIG_ACTIVATION,
    INDEX_OF_AUX_S4_DIG_P_DIG_ACTIVATION_DELAY,
    INDEX_OF_AUX_S4_DIG_P_SHUTDOWN,
    INDEX_OF_AUX_S4_DIG_P_SHUTDOWN_THRESHOLD,
    INDEX_OF_AUX_S4_DIG_P_NOTIFICATION,
    INDEX_OF_AUX_S4_DIG_P_NOTIFICATION_THRESHOLD,
    INDEX_OF_AUX_S4_DIG_P_FUEL_THEFT_WARNING,
    INDEX_OF_AUX_S4_DIG_P_FUEL_THEFT_THRESHOLD,
    INDEX_OF_AUX_S4_DIG_P_FUEL_CONSUMPTION,
    INDEX_OF_AUX_S4_DIG_P_FUEL_IN_PCT,
    INDEX_OF_AUX_S4_DIG_P_SENSOR_LOW_VTG,
    INDEX_OF_AUX_S4_DIG_P_SENSOR_HIGH_VTG,
    INDEX_OF_AUX_S4_DIG_P_TANK_WITH_STEP,
    INDEX_OF_AUX_S4_DIG_P_TANK_WIDTH,
    INDEX_OF_AUX_S4_DIG_P_TANK_LENGTH_1,
    INDEX_OF_AUX_S4_DIG_P_TANK_HEIGHT_1,
    INDEX_OF_AUX_S4_DIG_P_TANK_LENGTH_2,
    INDEX_OF_AUX_S4_DIG_P_TANK_HEIGHT_2,

    INDEX_OF_DIG_IN_Q_SOURCE,
    INDEX_OF_DIG_IN_Q_POLARITY,
    INDEX_OF_DIG_IN_Q_ACTION,
    INDEX_OF_DIG_IN_Q_ACTIVATION,
    INDEX_OF_DIG_IN_Q_ACTIVATION_DELAY,

    INDEX_OF_DIG_IN_R_SOURCE,
    INDEX_OF_DIG_IN_R_POLARITY,
    INDEX_OF_DIG_IN_R_ACTION,
    INDEX_OF_DIG_IN_R_ACTIVATION,
    INDEX_OF_DIG_IN_R_ACTIVATION_DELAY,
    /*Outputs menu*/
    INDEX_OF_OUT_A_SOURCE,
    INDEX_OF_OUT_A_ON_ACTIVATION,

    INDEX_OF_OUT_B_SOURCE,
    INDEX_OF_OUT_B_ON_ACTIVATION,

    INDEX_OF_OUT_C_SOURCE,
    INDEX_OF_OUT_C_ON_ACTIVATION,

    INDEX_OF_OUT_D_SOURCE,
    INDEX_OF_OUT_D_ON_ACTIVATION,

    INDEX_OF_OUT_E_SOURCE,
    INDEX_OF_OUT_E_ON_ACTIVATION,

    INDEX_OF_OUT_F_SOURCE,
    INDEX_OF_OUT_F_ON_ACTIVATION,

    INDEX_OF_OUT_G_SOURCE,
    INDEX_OF_OUT_G_ON_ACTIVATION,

    INDEX_OF_OUT_H_SOURCE,
    INDEX_OF_OUT_H_ON_ACTIVATION,

    INDEX_OF_OUT_I_SOURCE,
    INDEX_OF_OUT_I_ON_ACTIVATION,
    /*Timers menu*/
    INDEX_OF_CRANKING_TIMER_CRANK_HOLD_TIME,
    INDEX_OF_CRANKING_TIMER_CRANK_REST_TIME,
    INDEX_OF_CRANKING_TIMER_MANUAL_START_DELAY,
    INDEX_OF_CRANKING_TIMER_AUTO_START_DELAY,

    INDEX_OF_GENERAL_TIMER_SAFETY_MONITOR_DELAY,
    INDEX_OF_GENERAL_TIMER_MAINS_DETECT_DELAY,
    INDEX_OF_GENERAL_TIMER_ALT_DETECT_DELAY,
    INDEX_OF_GENERAL_TIMER_WARM_UP_DELAY,
    INDEX_OF_GENERAL_TIMER_RETN_TO_MAINS_DELAY,
    INDEX_OF_GENERAL_TIMER_ENG_COOL_TIME,
    INDEX_OF_GENERAL_TIMER_STOP_ACTION_TIME,
    INDEX_OF_GENERAL_TIMER_ADDN_STOPPING_TIME,
    INDEX_OF_GENERAL_TIMER_LOAD_TRANSFER_DELAY,
    INDEX_OF_GENERAL_TIMER_PWR_SAVE_MODE_DELAY,
    INDEX_OF_GENERAL_TIMER_SCRN_CHNGOVER_TIME,
    INDEX_OF_GENERAL_TIMER_SOUNDER_ALARM_TIMER,
    INDEX_OF_GENERAL_TIMER_TEST_MODE_TIMER,

    /*Generator menu*/
    INDEX_OF_ALT_CONFIG_ALT_PRESENT,
    INDEX_OF_ALT_CONFIG_NUMBER_OF_POLES,
    INDEX_OF_ALT_CONFIG_ALT_AC_SYSTEM,
    INDEX_OF_ALT_CONFIG_MIN_HEALTHY_VOLT,
    INDEX_OF_ALT_CONFIG_MIN_HEALTHY_FREQ,
    INDEX_OF_ALT_CONFIG_PHASE_REVERSAL_DETECT,
    INDEX_OF_ALT_CONFIG_PHASE_REVERSAL_ACTION,
    INDEX_OF_ALT_CONFIG_AUTO_LOAD_TRANSFER,
    INDEX_OF_ALT_CONFIG_ALT_WAVE_DETECTION,

    INDEX_OF_VOLT_MONITOR_UNDER_VOLT_SHUTDOWN,
    INDEX_OF_VOLT_MONITOR_UV_SHUTDOWN_THRESHOLD,
    INDEX_OF_VOLT_MONITOR_UNDER_VOLT_WARNING,
    INDEX_OF_VOLT_MONITOR_UV_WARNING_THRESHOLD,
    INDEX_OF_VOLT_MONITOR_OVER_VOLT_SHUTDOWN,
    INDEX_OF_VOLT_MONITOR_OV_SHUTDOWN_THRESHOLD,
    INDEX_OF_VOLT_MONITOR_OVER_VOLT_WARNING,
    INDEX_OF_VOLT_MONITOR_OV_WARNING_THRESHOLD,

    INDEX_OF_FREQ_MONITOR_UNDER_FREQ_SHUTDOWN,
    INDEX_OF_FREQ_MONITOR_UF_SHUTDOWN_THRESHOLD,
    INDEX_OF_FREQ_MONITOR_UNDER_FREQ_WARNING,
    INDEX_OF_FREQ_MONITOR_UF_WARNING_THRESHOLD,
    INDEX_OF_FREQ_MONITOR_OVER_FREQ_SHUTDOWN,
    INDEX_OF_FREQ_MONITOR_OF_SHUTDOWN_THRESHOLD,
    INDEX_OF_FREQ_MONITOR_OVER_FREQ_WARNING,
    INDEX_OF_FREQ_MONITOR_OF_WARNING_THRESHOLD,

    INDEX_OF_CURRENT_MONITOR_LOAD_CT_RATIO,
    INDEX_OF_CURRENT_MONITOR_OVER_CURR_ACTION,
    INDEX_OF_CURRENT_MONITOR_OVER_CURR_THRESHOLD,
    INDEX_OF_CURRENT_MONITOR_OVER_CURR_DELAY,
    INDEX_OF_CURRENT_MONITOR_CT_CORRECTION_FACTOR,
    INDEX_OF_CURRENT_MONITOR_CT_LOCATION,

    INDEX_OF_FAN_CURR_MONITOR_FAN_CURRENT_MON,
    INDEX_OF_FAN_CURR_MONITOR_FAN_MON_CT_RATIO,
    INDEX_OF_FAN_CURR_MONITOR_HIGH_CURR_THRESHOLD,
    INDEX_OF_FAN_CURR_MONITOR_HIGH_CURR_ACTION,
    INDEX_OF_FAN_CURR_MONITOR_LOW_CURR_THRESHOLD,
    INDEX_OF_FAN_CURR_MONITOR_LOW_CURR_ACTION,
    INDEX_OF_FAN_CURR_MONITOR_CURR_MON_DELAY,

    INDEX_OF_LOAD_MONITOR_GEN_RATING,
    INDEX_OF_LOAD_MONITOR_FULL_LOAD_CURRENT,
    INDEX_OF_LOAD_MONITOR_OVERLOAD_ACTION,
    INDEX_OF_LOAD_MONITOR_OVERLOAD_THRESHOLD,
    INDEX_OF_LOAD_MONITOR_OVERLOAD_MON_DELAY,
    INDEX_OF_LOAD_MONITOR_UNBAL_LOAD_ACTION,
    INDEX_OF_LOAD_MONITOR_UNBAL_LOAD_THRESHOLD,
    INDEX_OF_LOAD_MONITOR_UNBAL_LOAD_DELAY,
    INDEX_OF_LOAD_MONITOR_UNBAL_LOAD_ACT_THRESH,
    /*Mains menu*/
    INDEX_OF_MAINS_CONFIG_MAINS_MONITORING,
    INDEX_OF_MAINS_CONFIG_MAINS_AC_SYSTEM,
    INDEX_OF_MAINS_CONFIG_PHASE_REVERSAL_DETECT,
    INDEX_OF_MAINS_CONFIG_PHASE_REVERSAL_ACTION,
    INDEX_OF_MAINS_CONFIG_3PH_CALC_EN_FOR_1PH,

    INDEX_OF_UNDER_VOLT_MON_ENABLE,
    INDEX_OF_UNDER_VOLT_MON_TRIP,
    INDEX_OF_UNDER_VOLT_MON_RETURN,

    INDEX_OF_OVER_VOLT_MON_ENABLE,
    INDEX_OF_OVER_VOLT_MON_TRIP,
    INDEX_OF_OVER_VOLT_MON_RETURN,

    INDEX_OF_UNDER_FREQ_MON_ENABLE,
    INDEX_OF_UNDER_FREQ_MON_TRIP,
    INDEX_OF_UNDER_FREQ_MON_RETURN,

    INDEX_OF_OVER_FREQ_MON_ENABLE,
    INDEX_OF_OVER_FREQ_MON_TRIP,
    INDEX_OF_OVER_FREQ_MON_RETURN,
    /*Engine menu*/
    INDEX_OF_CRANK_DISCONN_START_ATTEMPTS,
    INDEX_OF_CRANK_DISCONN_DISCONN_ON_LOP_SENS,
    INDEX_OF_CRANK_DISCONN_DISCONN_LOP_SENS,
    INDEX_OF_CRANK_DISCONN_MON_LLOP_BEFORE_CRNK,
    INDEX_OF_CRANK_DISCONN_MON_LOP_BEFORE_CRANK,
    INDEX_OF_CRANK_DISCONN_DISCONN_ON_LLOP_SW,
    INDEX_OF_CRANK_DISCONN_LLOP_SW_TRANS_TIME,
    INDEX_OF_CRANK_DISCONN_ALT_FREQUENCY,
    INDEX_OF_CRANK_DISCONN_ENGINE_SPEED,
    INDEX_OF_CRANK_DISCONN_DISCONN_ON_CHG_ALT_VOLT,
    INDEX_OF_CRANK_DISCONN_CHG_ALT_THRESHOLD,

    INDEX_OF_SPEED_MONITOR_SPEED_SENSE_SOURCE,
    /*INDEX_OF_SPEED_MONITOR_RESERVED,*/
    INDEX_OF_SPEED_MONITOR_UNDER_SPEED_SHUTDOWN,
    INDEX_OF_SPEED_MONITOR_UNDER_SPEED_THRESHOLD,
    INDEX_OF_SPEED_MONITOR_UNDER_SPEED_DELAY,
    INDEX_OF_SPEED_MONITOR_OVER_SPEED_THRESHOLD,
    INDEX_OF_SPEED_MONITOR_OVER_SPEED_DELAY,
    INDEX_OF_SPEED_MONITOR_GROSS_OS_THRESHOLD,

    INDEX_OF_BATTERY_MONITOR_LOW_VOLT_ACTION,
    INDEX_OF_BATTERY_MONITOR_LOW_VOLT_THRESHOLD,
    INDEX_OF_BATTERY_MONITOR_LOW_VOLT_DELAY,
    INDEX_OF_BATTERY_MONITOR_HIGH_VOLT_ACTION,
    INDEX_OF_BATTERY_MONITOR_HIGH_VOLT_THRESHOLD,
    INDEX_OF_BATTERY_MONITOR_HIGH_VOLT_DELAY,

    INDEX_OF_CHARGE_ALT_MON_FAIL_ACTION,
    INDEX_OF_CHARGE_ALT_MON_FAIL_THRESHOLD,
    INDEX_OF_CHARGE_ALT_MON_FAIL_DELAY,

    INDEX_OF_PREHEAT_PREHEAT_TIMER,
    INDEX_OF_PREHEAT_ENG_TEMPERATURE,
    INDEX_OF_PREHEAT_ENG_TEMP_THRESHOLD,
    INDEX_OF_PREHEAT_AMB_TEMPERATURE,

    INDEX_OF_ENGINE_TYPE,
    INDEX_OF_ENG_SPEED_FROM_ECU,
    INDEX_OF_LOP_FROM_ECU,
    INDEX_OF_COOLANT_TEMP_FROM_ECU,
    INDEX_OF_ENG_RUN_HOURS_FROM_ECU,
    INDEX_OF_BAT_VTG_FROM_ECU,
    INDEX_OF_OIL_TEMP_FROM_ECU,
    INDEX_OF_COMM_FAIL_ALARM_ACTION,
    INDEX_OF_COMM_FAIL_ALARM_ACT,
    INDEX_OF_COMM_FAIL_ALARM_ACT_DELAY,
    INDEX_OF_AMBER_LAMP_ACTION,
    INDEX_OF_AMBER_LAMP_ACT,
    INDEX_OF_AMBER_LAMP_ACT_DELAY,
    INDEX_OF_RED_LAMP_ACTION,
    INDEX_OF_RED_LAMP_ACT,
    INDEX_OF_RED_LAMP_ACT_DELAY,
    INDEX_OF_MALFUNCTION_LAMP_ACTION,
    INDEX_OF_MALFUNCTION_LAMP_ACT,
    INDEX_OF_MALFUNCTION_LAMP_ACT_DELAY,
    INDEX_OF_PROTECT_LAMP_ACTION,
    INDEX_OF_PROTECT_LAMP_ACT,
    INDEX_OF_PROTECT_LAMP_ACT_DELAY,
    INDEX_OF_SGC_SOURCE_ADDRESS,
    INDEX_OF_ECU_SOURCE_ADDRESS,
    INDEX_OF_LOP_SHUTDOWN_EN,
    INDEX_OF_LOP_SHUTDOWN_THRESH,
    INDEX_OF_LOP_WARNING_EN,
    INDEX_OF_LOP_WARNING_THRESH,
    INDEX_OF_HWT_SHUTDOWN_EN,
    INDEX_OF_HWT_SHUTDOWN_THRESH,
    INDEX_OF_HWT_WARNING_EN,
    INDEX_OF_HWT_WARNING_THRESH,
    INDEX_OF_HIGH_OIL_TEMP_SHUTDOWN_EN_FROM_ECU,
    INDEX_OF_HIGH_OIL_TEMP_SHUTDOWN_THRESH_FROM_ECU,
    INDEX_OF_HIGH_OIL_TEMP_WARNING_EN_FROM_ECU,
    INDEX_OF_HIGH_OIL_TEMP_WARNING_THRESH_FROM_ECU,

    /*EGR Timers Menu*/
    INDEX_OF_ENABLE_EGR_TIMERS,
    INDEX_OF_FAULT_SHUTDOWN_TIMER,
    INDEX_OF_FAULT_WARNING_TIMER,
    INDEX_OF_HEAL_TIMER,

    /*Maintenance menu*/
    INDEX_OF_MAINT_ALARM_ACTION,
    INDEX_OF_MAINT_ALARM_DUE_AT_ENGINE_HOURS,

    INDEX_OF_ALARM_DUE_DATE_SERVICE_DATE,

    /*ID menu*/
    INDEX_OF_ENG_SR_NO,

    INDEX_OF_PIN_1,

    INDEX_OF_PIN_2,

    /*Select Profile menu*/
    INDEX_OF_ACTIVE_PROFILE,

    INDEX_LAST
};

#define NUM_OF_MENU_ITEMS_AT_MID_LEVEL  ID_SUB_MENU_LAST
#define NUM_OF_MENU_ITEMS_AT_TOP_LEVEL  ID_MAIN_MENU_LAST

#endif /* _CONFIGURATION_H_ */
